version: '3.9'
networks:
  net:
    driver: bridge
services:
  indexer_service:
    build: ./indexer_service
    ports:
      - "4000:5000"
    networks:
      - net
    environment:
      INDEX_NAME: "developers"
      MONGO_URI: "******************************"
      DB_NAME: "codespread"
      COLLECTION_NAME: "developers"
      MODEL_NAME: "BAAI/bge-base-en-v1.5"
      OPENAI_API_KEY: "***********************"
    depends_on:
      - chroma
  query_service:
    build: ./query_service
    environment:
     INDEX_NAME: "developers"
     MODEL_NAME: "BAAI/bge-base-en-v1.5"
     OPENAI_API_KEY: "*******************"
    ports:
      - "4001:5001"
    networks:
      - net
    depends_on:
        - chroma
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - index_data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net
volumes:
  backups:
    driver: local
  index_data:
    driver: local



#MONGO_URI = os.getenv('MONGO_URI')
#DB_NAME = os.getenv('DB_NAME', 'codespread')
#COLLECTION_NAME = os.getenv('COLLECTION_NAME', 'developers')
#INDEX_NAME = os.getenv('INDEX_NAME', 'default-index')
#MODEL_NAME = os.getenv('MODEL_NAME', 'BAAI/bge-base-en-v1.5')