version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_config.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
